/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInquiry {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'serviceInterest' : ServiceInterest,
  'message' : string,
  'timestamp' : bigint,
  'organization' : string,
  'phone' : string,
}
export type ServiceInterest = { 'other' : null } |
  { 'erp_implementation' : null } |
  { 'cloud_services' : null } |
  { 'cyber_security' : null } |
  { 'managed_it' : null };
export interface Testimonial {
  'id' : bigint,
  'clientName' : string,
  'designation' : string,
  'testimonialText' : string,
  'company' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'addTestimonial' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'getAllInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getInquiryCount' : ActorMethod<[], bigint>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, ServiceInterest, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];