/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceInterest = IDL.Variant({
  'other' : IDL.Null,
  'erp_implementation' : IDL.Null,
  'cloud_services' : IDL.Null,
  'cyber_security' : IDL.Null,
  'managed_it' : IDL.Null,
});
export const ContactInquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'serviceInterest' : ServiceInterest,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'organization' : IDL.Text,
  'phone' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'clientName' : IDL.Text,
  'designation' : IDL.Text,
  'testimonialText' : IDL.Text,
  'company' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getInquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitInquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ServiceInterest,
        IDL.Text,
        IDL.Int,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceInterest = IDL.Variant({
    'other' : IDL.Null,
    'erp_implementation' : IDL.Null,
    'cloud_services' : IDL.Null,
    'cyber_security' : IDL.Null,
    'managed_it' : IDL.Null,
  });
  const ContactInquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'serviceInterest' : ServiceInterest,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'organization' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'clientName' : IDL.Text,
    'designation' : IDL.Text,
    'testimonialText' : IDL.Text,
    'company' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getInquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitInquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ServiceInterest,
          IDL.Text,
          IDL.Int,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };